### ISSUE TITLE
AkamaiOPEN-edgegrid-node follows redirects

### ISSUE THREAD

**Issue by mdb** [JonathanBennett/AkamaiOPEN-edgegrid-node#14]
When an Akamai API request returns a response with a status code indicating a redirect, AkamaiOPEN-edgegrid-node automatically follows the redirect, but fails to generate a new `Authorization` header based on the `Location`. As a result, the request fails, returning a response status code of `401` ("The signature does not match").

This can be reproduced by performing a request against the PAPI latest property version endpoint:
```
var eg = new EdgeGrid(clientToken, clientSecret, accessToken, base);

eg.auth({
  path: '/papi/v0/properties/prp_123/versions/latest?contractId=ctr_123&groupId=grp_123&activatedOn=STAGING'
});

eg.send(function (data, response) {
  console.log(data);
});
```

**Comment by JonathanBennett** [comment]
Closing this now as merged PR. Thanks @mdb.
