### ISSUE TITLE
DEBUG data and INFO are logged, containing private credentials

### ISSUE THREAD

**Issue by mdb** [JonathanBennett/AkamaiOPEN-edgegrid-node#5]
Despite that the log level is [apparently set to ERROR](https://github.com/JonathanBennett/AkamaiOPEN-edgegrid-node/blob/master/src/auth.js#L15), I see `console.info` and `console.debug` data logged.

In my mind, this is somewhat problematic, as I would prefer not to log my Akamai API credentials.

Please let me know if I'm overlooking something.

Thanks!

**Comment by JonathanBennett** [comment]
Closing as this is now merged. Thanks for the pull request @mdb
