### ISSUE TITLE
Instantiation does not properly log an error if edgegridrc `path` is falsey.

### ISSUE THREAD

**Issue by mdb** [JonathanBennett/AkamaiOPEN-edgegrid-node#9]
In current implementation, `AkamaiOPEN-edgegrid-node` explicitly [checks for an undefined `path`](https://github.com/JonathanBennett/AkamaiOPEN-edgegrid-node/blob/master/src/api.js#L54).

However, it is my belief that this is inadequate, as the `path` could also be an empty string, a boolean, or a non-string value. In my mind, simply checking for `!path` is preferable.

I am working on a PR/tests addressing this issue. See my [edgerc-cleanup](https://github.com/mdb/AkamaiOPEN-edgegrid-node/tree/edgerc-cleanup) branch for further details.

Thanks!

**Comment by mdb** [comment]
I believe this issue can be closed.

**Comment by JonathanBennett** [comment]
Thanks @mdb
